# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-04-10 20:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lockSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_locked', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Comment_user_like',
        ),
        migrations.AddField(
            model_name='article',
            name='comments_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='article',
            name='tag_name',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_comment_like',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='art_number_views',
            field=models.IntegerField(default=0, verbose_name='view count'),
        ),
        migrations.AlterField(
            model_name='article',
            name='art_publish_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='publish date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='art_status',
            field=models.CharField(choices=[('d', 'Drafts'), ('p', 'Published'), ('a', 'Approved')], default='d', max_length=1, verbose_name='publish status'),
        ),
        migrations.AlterField(
            model_name='article',
            name='art_title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='art_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='banwords',
            name='banword_name',
            field=models.CharField(max_length=255, verbose_name='BanWord'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Comment_parent_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Comment_status',
            field=models.BooleanField(default=1, verbose_name='Is Approved'),
        ),
    ]
