# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-04-13 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20160413_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tag_name',
        ),
    ]
